### ISSUE TITLE
README Wiki Link

### ISSUE THREAD

**Issue by Zeus432** [BSOD2528/Geralt#1]
the Wiki link in [Line 30 in Geralt's Readme](https://github.com/BSOD2528/Geralt/blob/main/README.md) redirects to https://github.com/BSOD2528/Geralt instead of https://github.com/BSOD2528/Geralt/wiki which is the proper link to the wiki page

- [ ] Fix Wiki Link

**Comment by BSOD2528** [comment]
> the Wiki link in [Line 30 in Geralt's Readme](https://github.com/BSOD2528/Geralt/blob/main/README.md) redirects to https://github.com/BSOD2528/Geralt instead of https://github.com/BSOD2528/Geralt/wiki which is the proper link to the wiki page
> 
> * [ ]  Fix Wiki Link

Yes, while creating the first version of the readme I had wantedly [ I hope thats the right spelling ] done this as I need some time to prepare with academics and didnt have the time to create a wiki page 🙏🏼
